export const GET_JADWAL_PELAJARAN_BY_ID_KELAS = "GET_JADWAL_PELAJARAN_BY_ID_KELAS";
export const GET_JADWAL_PELAJARAN_FOR_SISWA = "GET_JADWAL_PELAJARAN_FOR_SISWA";
export const GET_ABSEN_FOR_SISWA = "GET_ABSEN_FOR_SISWA";