export const GET_DATA_NILAI_ADMIN = "GET_DATA_NILAI_ADMIN";
export const GET_DATA_NILAI_SISWA = "GET_DATA_NILAI_SISWA";
export const GET_DATA_NILAI_BY_ID_KELAS = "GET_DATA_NILAI_BY_ID_KELAS";
export const ADD_DATA_NILAI_SISWA = "ADD_DATA_NILAI_SISWA";