export const GET_ALL_DATA_PERTEMUAN = "GET_DATA_PERTEMUAN";
export const GET_ALL_DATA_PERTEMUAN_BY_ID_MAPEL = "GET_ALL_DATA_PERTEMUAN_BY_ID_MAPEL";
export const GET_DATA_PERTEMUAN = "GET_DATA_PERTEMUAN";
export const GET_DATA_ABSENSI_BY_MAPEL_PERTEMUAN = "GET_DATA_ABSENSI_BY_MAPEL_PERTEMUAN";
export const GET_DATA_ABSENSI = "GET_DATA_ABSENSI";